FROM node:20-alpine

WORKDIR /app

# 의존성 파일 복사 및 설치
COPY package.json ./
RUN npm install

# 소스 코드 복사
COPY . .

# 환경 변수 설정
ENV NODE_ENV=development
ENV HOSTNAME=0.0.0.0

# 노출 포트
EXPOSE 3000

# 서버 실행 (모든 IP에서 접근 가능하도록 설정)
CMD ["npx", "next", "dev", "-H", "0.0.0.0"] 