version: '3'

services:
  nextjs:
    container_name: smap_next_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://118.67.130.71:83/api
      - HOSTNAME=0.0.0.0
    networks:
      - smap_next_network
    volumes:
      - next_build:/app/.next
      - ./frontend/public:/app/public
      - ./frontend/src:/app/src
    depends_on:
      - backend

  backend:
    container_name: smap_next_backend
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    restart: always
    ports:
      - "5001:5000"
    environment:
      - NODE_ENV=production
      - CORS_ORIGIN=http://118.67.130.71:83
      - DB_HOST=${DB_HOST:-host.docker.internal}
      - DB_USER=${DB_USER:-smap2}
      - DB_PASSWORD=${DB_PASSWORD:-dmonster}
      - DB_NAME=${DB_NAME:-smap2_db}
      - DB_PORT=${DB_PORT:-3306}
      - DB_TYPE=${DB_TYPE:-mysql}
    networks:
      - smap_next_network
    volumes:
      - ./backend/app:/app/app
      - ./backend/requirements.txt:/app/requirements.txt
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  smap_next_network:
    driver: bridge

volumes:
  next_build: 