version: '3'

services:
  nextjs:
    container_name: smap_next_frontend
    build:
      context: .
      dockerfile: frontend/Dockerfile.prod
    restart: always
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
      HOSTNAME: 0.0.0.0
      INTERNAL_BACKEND_URL: ${INTERNAL_BACKEND_URL:-http://backend:5000}
    networks:
      - smap_next_network
    volumes:
      - next_build:/app/.next
    depends_on:
      - backend

  backend:
    container_name: smap_next_backend
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    restart: always
    ports:
      - "8000:5000"
    networks:
      - smap_next_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - ./backend:/app
    extra_hosts:
      - "host.docker.internal:host-gateway" # For Linux to resolve host.docker.internal

networks:
  smap_next_network:
    driver: bridge

volumes:
  next_build: 