version: '3'

services:
  nextjs:
    container_name: smap_next_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    restart: always
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://118.67.130.71:83/api
    networks:
      - smap_next_network
    volumes:
      - next_build:/app/.next
      - ./frontend/public:/app/public
    depends_on:
      - backend

  backend:
    container_name: smap_next_backend
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    restart: always
    ports:
      - "5001:5000"
    environment:
      - NODE_ENV=production
      - CORS_ORIGIN=http://118.67.130.71:83
      - DB_HOST=host.docker.internal
      - DB_USER=smap2
      - DB_PASSWORD=dmonster
      - DB_NAME=smap2_db
      - DB_PORT=3306
      - DB_TYPE=mysql
    networks:
      - smap_next_network
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  smap_next_network:
    driver: bridge

volumes:
  next_build: 