version: '3'

services:
  nextjs:
    container_name: smap_next_frontend_dev
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
      HOSTNAME: 0.0.0.0
      INTERNAL_BACKEND_URL: ${INTERNAL_BACKEND_URL:-http://backend:5000}
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"
    networks:
      - smap_next_network
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - backend

  backend:
    container_name: smap_next_backend_dev
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    ports:
      - "8000:5000"
    networks:
      - smap_next_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - ./backend:/app
    environment:
      - ENVIRONMENT=development
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    extra_hosts:
      - "host.docker.internal:host-gateway" # For Linux to resolve host.docker.internal

networks:
  smap_next_network:
    driver: bridge 