from sqlalchemy import Column, Integer, String, DateTime, Double, Text, Enum as SQLEnum
from sqlalchemy.ext.declarative import declarative_base
from app.db.base_class import Base

class Order(Base):
    __tablename__ = "order_t"
    
    ot_idx = Column(Integer, primary_key=True, index=True, autoincrement=True)
    ot_code = Column(String(100), index=True, comment="주문번호")
    ot_ori_code = Column(String(255), comment="기존 주문번호")
    mt_idx = Column(Integer, index=True, comment="주문 회원idx")
    mt_id = Column(String(50), index=True, comment="주문 회원ID")
    ot_title = Column(String(255), comment="타이틀")
    ot_pay_type = Column(String(10), index=True, comment="결제방법 (1:신규가입 2:앱결제 3:쿠폰 4:추천인)")
    ot_sdate = Column(DateTime, comment="플랜시작일")
    ot_edate = Column(DateTime, comment="플랜종료일")
    ot_status = Column(Integer, index=True, comment="주문상태(1:결재대기, 2:결제완료, 99:취소)")
    ot_sprice = Column(Double, comment="상품합계")
    ot_use_coupon = Column(Double, comment="사용쿠폰금액")
    ot_coupon_idx = Column(Integer, comment="사용쿠폰idx")
    ot_price = Column(Double, comment="결제금액")
    ot_price_b = Column(Double, comment="쿠폰 차감안된 결제금액")
    ot_pay_bank = Column(String(100), comment="무통장 입금 은행정보")
    ot_rsp_imp_uid = Column(String(20), index=True, comment="포트원 고유번호")
    ct_cancel_amount = Column(Double, comment="포트원 환불 요청금액")
    ct_cancel_reson = Column(String(50), comment="포트원 환불 사유")
    ct_refund_holder = Column(String(50), comment="포트원 환불 가상계좌 예금주")
    ct_refund_bank = Column(String(50), comment="포트원 환불 가상계좌 은행")
    ct_refund_account = Column(String(50), comment="포트원 환불 가상계좌 계좌번호")
    ot_wdate = Column(DateTime, index=True, comment="주문일시")
    ot_pdate = Column(DateTime, index=True, comment="결제일시")
    ot_cdate = Column(DateTime, index=True, comment="구매확정일시")
    ot_ccdate = Column(DateTime, index=True, comment="취소완료일시")
    ot_refund_info = Column(String(255), comment="환불정보")
    ot_show = Column(SQLEnum('Y', 'N', name='show_enum'), index=True, comment="주문노출여부")
    ot_memo = Column(Text, comment="관리자메모")
    ot_udate = Column(DateTime, comment="관리자수정일시")
    ot_cash_name = Column(String(50), comment="현금영수증 이름")
    ot_cash_hp = Column(String(50), comment="현금영수증 연락처")
    ot_cash_chk = Column(String(5), comment="현금영수증 발행여부")
    vbank_date = Column(DateTime, comment="가상계좌 결제") 