# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'smap' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # WebView 관련 의존성
  pod 'WebKit'
  
  # 네트워킹
  pod 'Alamofire', '~> 5.5'
  
  # 키보드 관리
  pod 'IQKeyboardManagerSwift'
  
  # Firebase 관련 (푸시 알림 등)
  pod 'Firebase/Auth'
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  
  # UI 관련
  pod 'SnackBar.swift'
  
  # 인앱 결제
  pod 'SwiftyStoreKit'
  
  # 광고 (필요시)
  pod 'Google-Mobile-Ads-SDK'
  
  # Pods for smap

end 